### ISSUE TITLE
Main todo list

### ISSUE THREAD

**Issue by AoifeHughes** [AoifeHughes/PoliwhiRL#1]
- [ ] Define library to use 
- [ ] Setup training loop
- [ ] Define success criteria / reward design
- [ ] Define Action representation 
- [ ] Define Action space 
- [ ] Implement emulator image -> software pipeline.
- [ ] Implement input pipeline
